"use client";
import React, { useState, useRef, useEffect } from "react";

const TRANSLATIONS = {
  zh: {
    name: "简体中文",
    badge: "✦ AI创作工坊",
    title1: "一键生成",
    title2: "小说 · 文案",
    subtitle: "输入想法，AI帮你写出完整内容",
    authLabel: "已激活：剩余 30 天",
    modeLabel: "创作类型",
    modes: [
      { id: "novel", label: "📖 小说", desc: "完整故事情节" },
      { id: "copy", label: "✍️ 文案", desc: "营销推广文字" },
      { id: "script", label: "🎬 剧本", desc: "对话场景脚本" },
      { id: "post", label: "📱 种草", desc: "小红书/抖音文案" },
    ],
    ideaLabel: "💡 你的想法 *",
    ideaPlaceholders: {
      novel: "例如：一个失忆侦探发现自己就是凶手...",
      copy: "例如：主打成分护肤的精华液，目标用户25-35岁女性...",
      script: "例如：两个多年未见的老友重逢，发现彼此都变了...",
      post: "例如：用番茄工作法让效率翻倍的亲身经历...",
    },
    genreLabel: "题材类型",
    copyTypeLabel: "文案类型",
    postLabel: "目标平台",
    genres: ["言情", "悬疑", "玄幻", "都市", "历史", "科幻", "恐怖", "励志"],
    copyTypes: ["产品推广", "品牌故事", "活动营销", "朋友圈", "广告语", "软文"],
    postTypes: ["小红书", "抖音", "微信公众号", "微博", "视频号"],
    lengthLabel: "字数",
    styleLabel: "风格",
    extraLabel: "额外要求（选填）",
    extraPlaceholder: "例如：主角叫小月，结局要开心，语气要活泼...",
    lengths: [
      { v: "short", l: "短篇（500字）" },
      { v: "medium", l: "中篇（1500字）" },
      { v: "long", l: "长篇（3000字）" },
    ],
    styles: ["正式严肃", "轻松幽默", "文艺感性", "犀利直接", "温暖治愈", "悬疑紧张"],
    styleDefault: "不限风格",
    btnGenerate: "✨ 开始创作",
    btnGenerating: "⏳ 创作中...",
    btnCopy: "复制全文",
    btnCopied: "✓ 已复制",
    resultLabel: "创作结果",
    resultLabels: { novel: "📖 小说正文", copy: "✍️ 文案内容", script: "🎬 剧本内容", post: "📱 种草内容" },
    streaming: "正在创作...",
    placeholder1: "在左侧输入你的想法",
    placeholder2: "AI 将为你生成完整内容",
    tags: ["灵感无限", "流畅输出", "一键复制"],
    thinking: "AI 正在构思创作...",
    errEmpty: "请输入你的想法或创意",
    errFail: "生成失败：",
    errRetry: "请求失败，请稍后重试",
    lengthMap: { short: "500字左右", medium: "1500字左右", long: "3000字左右" },
    systemPrompts: {
      novel: "你是一位顶级小说作家，擅长各类题材。文字生动、情节紧凑、人物立体。直接输出小说正文，不要加任何说明或前缀。",
      copy: "你是顶级文案策划师，擅长各类营销文案。文案有感染力、转化率高。直接输出文案正文。",
      script: "你是专业编剧，擅长对话、场景、冲突。剧本真实有张力。直接输出剧本内容。",
      post: "你是自媒体爆款文案专家，深度了解小红书、抖音平台 and 用户心理。直接输出内容正文。",
    },
    userPrompts: {
      novel: (idea, sel, len, style, extra) => `根据以下想法，创作一篇完整小说。\n\n想法：${idea}\n题材：${sel||"不限"}\n字数：${len}\n风格：${style||"不限"}\n要求：${extra||"无"}\n\n直接从标题开始输出小说内容，要有吸引人的开头、起伏的情节、有力量的结尾。`,
      copy: (idea, sel, len, style, extra) => `根据以下需求，创作专业文案。\n\n需求：${idea}\n类型：${sel||"通用推广"}\n字数：${len}\n风格：${style||"不限"}\n要求：${extra||"无"}\n\n要求标题吸引眼球、痛点精准、卖点突出、有行动引导。`,
      script: (idea, sel, len, style, extra) => `根据以下想法创作剧本。\n\n故事：${idea}\n风格：${sel||"不限"}\n长度：${len}\n风格：${style||"不限"}\n要求：${extra||"无"}\n\n格式：场景说明 + 人物对话（角色名：台词）+ 动作指示，有明确的戏剧冲突。`,
      post: (idea, sel, len, style, extra) => `根据以下想法创作爆款自媒体内容。\n\n内容：${idea}\n平台：${sel||"小红书"}\n字数：${len}\n风格：${style||"不限"}\n要求：${extra||"无"}\n\n要求：开头3行抓眼球、多用换行和emoji、有干货或情感共鸣、结尾引导互动、附上5个话题标签。`,
    },
  },
  tw: {
    name: "繁體中文",
    badge: "✦ AI創作工坊",
    title1: "一鍵生成",
    title2: "小說 · 文案",
    subtitle: "輸入想法，AI幫你寫出完整內容",
    authLabel: "已激活：剩餘 30 天",
    modeLabel: "創作類型",
    modes: [
      { id: "novel", label: "📖 小說", desc: "完整故事情節" },
      { id: "copy", label: "✍️ 文案", desc: "行銷推廣文字" },
      { id: "script", label: "🎬 劇本", desc: "對話場景腳本" },
      { id: "post", label: "📱 種草", desc: "社群媒體文案" },
    ],
    ideaLabel: "💡 你的想法 *",
    ideaPlaceholders: {
      novel: "例如：一個失憶偵探發現自己就是兇手...",
      copy: "例如：主打成分護膚的精華液，目標用戶25-35歲女性...",
      script: "例如：兩個多年未見的老友重逢，發現彼此都變了...",
      post: "例如：用番茄工作法讓效率翻倍的親身經歷...",
    },
    genreLabel: "題材類型",
    copyTypeLabel: "文案類型",
    postLabel: "目標平台",
    genres: ["言情", "懸疑", "玄幻", "都市", "歷史", "科幻", "恐怖", "勵志"],
    copyTypes: ["產品推廣", "品牌故事", "活動行銷", "社群貼文", "廣告語", "軟文"],
    postTypes: ["Instagram", "Facebook", "YouTube", "TikTok", "Threads"],
    lengthLabel: "字數",
    styleLabel: "風格",
    extraLabel: "額外要求（選填）",
    extraPlaceholder: "例如：主角叫小月，結局要開心，語氣要活潑...",
    lengths: [
      { v: "short", l: "短篇（500字）" },
      { v: "medium", l: "中篇（1500字）" },
      { v: "long", l: "
